"""Auto pipeline package.

Public surface matches the former ``app.workflow.auto_pipeline`` module so that
compatibility shims and tests can monkeypatch names on this package.
"""
from __future__ import annotations

import time

from .constants import (
    AUTO_ACTIVE_STATUSES,
    COPY_PRESET_THEME_PROFILES,
    COPY_PROMPT_PRESETS,
    IMAGE_REPAIR_BURST_SIZE,
    IMAGE_REPAIR_INFINITE_BURST_SIZE,
    IMAGE_REPAIR_SINGLE_RETRY_SIZE,
    RENDER_STALL_SECONDS,
    STEP_KEYS,
    AutoPipelineCancelled,
    AutoPipelineError,
    _ACTIVE_AUTO_IDS,
    _RENDER_STALL_MSG,
    _cancelled,
    _lock,
    _runner,
    _runtime_secrets,
)
from .presets import (
    _copy_preset_theme_instruction,
    _copy_preset_theme_profile,
    _default_copy_prompt,
    _default_copy_to_story_prompt,
    _default_image_prompt,
    _default_improve_prompt,
    _job_copy_preset,
    _resolve_copy_preset,
)
from .state import (
    _apply_repair_success,
    _check_cancelled,
    _clear_image_failure,
    _image_config,
    _image_failure_message,
    _image_repair_concurrency,
    _is_cancelled,
    _latest_job,
    _llm_config,
    _mark_cancelled,
    _mark_repair_failure,
    _missing_image_indexes,
    _public,
    _read,
    _save,
    _secrets,
    _set_step,
    _shot_has_image,
    _state_or_default,
    _step,
    _step_template,
    _story_has_valid_shots,
    _with_runtime_keys,
    _write_state,
)
from .image_repair import (
    _optimize_failed_image_prompt,
    _optimize_failed_image_prompts,
    _repair_burst_for_shots,
    _repair_missing_images,
)
from .steps import (
    _render_payload,
    _render_updated_seconds,
    _run_copy,
    _run_cover,
    _run_images,
    _run_improve_prompts,
    _run_render,
    _run_select_idea,
    _run_storyboard,
    _run_theme,
    _run_theme_ideas,
    _wait_image_job,
    _wait_render_job,
)
from .service import (
    _mark_auto_stale_if_orphaned,
    _run_pipeline,
    cancel_auto_pipeline_job,
    create_auto_pipeline_job,
    get_auto_pipeline_job,
    list_auto_pipeline_jobs,
    resume_auto_pipeline_job,
)

# Re-export dependencies that tests monkeypatch on this package.
from app.media.render.service import create_render_job, get_render_job

__all__ = [
    "AUTO_ACTIVE_STATUSES",
    "COPY_PRESET_THEME_PROFILES",
    "COPY_PROMPT_PRESETS",
    "IMAGE_REPAIR_BURST_SIZE",
    "IMAGE_REPAIR_INFINITE_BURST_SIZE",
    "IMAGE_REPAIR_SINGLE_RETRY_SIZE",
    "RENDER_STALL_SECONDS",
    "STEP_KEYS",
    "AutoPipelineCancelled",
    "AutoPipelineError",
    "_ACTIVE_AUTO_IDS",
    "_RENDER_STALL_MSG",
    "_apply_repair_success",
    "_cancelled",
    "_check_cancelled",
    "_clear_image_failure",
    "_copy_preset_theme_instruction",
    "_copy_preset_theme_profile",
    "_default_copy_prompt",
    "_default_copy_to_story_prompt",
    "_default_image_prompt",
    "_default_improve_prompt",
    "_image_config",
    "_image_failure_message",
    "_image_repair_concurrency",
    "_is_cancelled",
    "_job_copy_preset",
    "_latest_job",
    "_llm_config",
    "_lock",
    "_mark_auto_stale_if_orphaned",
    "_mark_cancelled",
    "_mark_repair_failure",
    "_missing_image_indexes",
    "_optimize_failed_image_prompt",
    "_optimize_failed_image_prompts",
    "_public",
    "_read",
    "_render_payload",
    "_render_updated_seconds",
    "_repair_burst_for_shots",
    "_repair_missing_images",
    "_resolve_copy_preset",
    "_run_copy",
    "_run_cover",
    "_run_images",
    "_run_improve_prompts",
    "_run_pipeline",
    "_run_render",
    "_run_select_idea",
    "_run_storyboard",
    "_run_theme",
    "_run_theme_ideas",
    "_runner",
    "_runtime_secrets",
    "_save",
    "_secrets",
    "_set_step",
    "_shot_has_image",
    "_state_or_default",
    "_step",
    "_step_template",
    "_story_has_valid_shots",
    "_wait_image_job",
    "_wait_render_job",
    "_with_runtime_keys",
    "_write_state",
    "cancel_auto_pipeline_job",
    "create_auto_pipeline_job",
    "create_render_job",
    "get_auto_pipeline_job",
    "get_render_job",
    "list_auto_pipeline_jobs",
    "resume_auto_pipeline_job",
    "time",
]
