"""Intro template package."""
from __future__ import annotations

from .constants import (
    EXPAND_CUT_INITIAL_HALF_HEIGHT,
    EXPAND_CUT_MASK_FEATHER,
    EXPAND_CUT_TEMPLATE,
    FAST_CUT_IMAGE_SECONDS,
    FAST_CUT_MASK_FEATHER,
    FAST_CUT_MAX_IMAGES,
    FAST_CUT_TEMPLATE,
    FLASH_CUT_MASK_FEATHER,
    FLASH_HORIZONTAL_TEMPLATE,
    FLASH_VERTICAL_TEMPLATE,
    INTRO_PREVIEW_TEMPLATES,
    INTRO_TEMPLATES,
    MOSAIC_COLLAGE_TEMPLATE,
    MOSAIC_TILE_COUNT,
    STAGGERED_MASK_FEATHER,
    STAGGERED_MASK_TEMPLATE,
    STAGGERED_SWEEP_MULTIPLIER,
)
from .common import normalize_intro_image_seconds, render_still_clip
from .templates import render_intro_template

__all__ = [
    "EXPAND_CUT_INITIAL_HALF_HEIGHT",
    "EXPAND_CUT_MASK_FEATHER",
    "EXPAND_CUT_TEMPLATE",
    "FAST_CUT_IMAGE_SECONDS",
    "FAST_CUT_MASK_FEATHER",
    "FAST_CUT_MAX_IMAGES",
    "FAST_CUT_TEMPLATE",
    "FLASH_CUT_MASK_FEATHER",
    "FLASH_HORIZONTAL_TEMPLATE",
    "FLASH_VERTICAL_TEMPLATE",
    "INTRO_PREVIEW_TEMPLATES",
    "INTRO_TEMPLATES",
    "MOSAIC_COLLAGE_TEMPLATE",
    "MOSAIC_TILE_COUNT",
    "STAGGERED_MASK_FEATHER",
    "STAGGERED_MASK_TEMPLATE",
    "STAGGERED_SWEEP_MULTIPLIER",
    "normalize_intro_image_seconds",
    "render_intro_template",
    "render_still_clip",
]
