"""LLM provider adapter package."""
from __future__ import annotations

from .constants import (
    ANTHROPIC_DEFAULT_BASE_URL,
    ANTHROPIC_DEFAULT_MODEL,
    COPY_TO_STORY_PROMPT_PATH,
    DEFAULT_LLM_BASE_URL,
    DEFAULT_PROMPT_PATH,
    DEFAULT_STORYBOARD_GRANULARITY,
    DEFAULT_TEXT_MODEL,
    GEMINI_DEFAULT_BASE_URL,
    GEMINI_DEFAULT_MODEL,
    IMPROVE_IMAGE_PROMPT_PATH,
    LLMConfig,
    LLMError,
    MISSING_API_KEY_MESSAGE,
    REFERENCE_SELECTION_PROMPT,
    REFERENCE_TYPE_PRIORITY,
    STORYBOARD_GRANULARITY_RULES,
    THEME_IDEAS_PROMPT_PATH,
    THEME_PROMPT_PATH,
)
from .prompts import (
    load_copy_to_story_prompt,
    load_default_prompt,
    load_improve_image_prompt,
    load_theme_ideas_prompt,
    load_theme_prompt,
)
from .client import _chat_text, _anthropic_text, _gemini_text, _provider_text
from .generation import (
    generate_story,
    generate_story_from_copy,
    generate_text,
    generate_theme_ideas,
    generate_topic_plan,
    improve_image_prompt,
    revise_topic_plan,
    test_text_connection,
)
from .references import select_primary_reference_asset

__all__ = [
    "ANTHROPIC_DEFAULT_BASE_URL",
    "ANTHROPIC_DEFAULT_MODEL",
    "COPY_TO_STORY_PROMPT_PATH",
    "DEFAULT_LLM_BASE_URL",
    "DEFAULT_PROMPT_PATH",
    "DEFAULT_STORYBOARD_GRANULARITY",
    "DEFAULT_TEXT_MODEL",
    "GEMINI_DEFAULT_BASE_URL",
    "GEMINI_DEFAULT_MODEL",
    "IMPROVE_IMAGE_PROMPT_PATH",
    "LLMConfig",
    "LLMError",
    "MISSING_API_KEY_MESSAGE",
    "REFERENCE_SELECTION_PROMPT",
    "REFERENCE_TYPE_PRIORITY",
    "STORYBOARD_GRANULARITY_RULES",
    "THEME_IDEAS_PROMPT_PATH",
    "THEME_PROMPT_PATH",
    "_anthropic_text",
    "_chat_text",
    "_gemini_text",
    "_provider_text",
    "generate_story",
    "generate_story_from_copy",
    "generate_text",
    "generate_theme_ideas",
    "generate_topic_plan",
    "improve_image_prompt",
    "load_copy_to_story_prompt",
    "load_default_prompt",
    "load_improve_image_prompt",
    "load_theme_ideas_prompt",
    "load_theme_prompt",
    "revise_topic_plan",
    "select_primary_reference_asset",
    "test_text_connection",
]
